title: Concrete CMS テーマ開発のベストプラクティス＆バッドプラクティス
author: 株式会社マカルーデジタル
email: info@macareux.co.jp
theme: minima
header_pages:
  - index.md
  - css-javascript.md
  - blocktypes.md
  - editor.md
  - layouts.md